// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// create_geometries.cpp
cpp11::list create_linestrings_cpp(cpp11::doubles x1, cpp11::doubles y1, cpp11::doubles x2, cpp11::doubles y2);
extern "C" SEXP _rrstools_create_linestrings_cpp(SEXP x1, SEXP y1, SEXP x2, SEXP y2) {
  BEGIN_CPP11
    return cpp11::as_sexp(create_linestrings_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y2)));
  END_CPP11
}
// create_geometries.cpp
cpp11::list create_face_multilinestrings_cpp(cpp11::list face_edge_hrefs, cpp11::strings edge_ids, cpp11::list edge_geoms);
extern "C" SEXP _rrstools_create_face_multilinestrings_cpp(SEXP face_edge_hrefs, SEXP edge_ids, SEXP edge_geoms) {
  BEGIN_CPP11
    return cpp11::as_sexp(create_face_multilinestrings_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(face_edge_hrefs), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(edge_ids), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(edge_geoms)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rrstools_create_face_multilinestrings_cpp", (DL_FUNC) &_rrstools_create_face_multilinestrings_cpp, 3},
    {"_rrstools_create_linestrings_cpp",           (DL_FUNC) &_rrstools_create_linestrings_cpp,           4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rrstools(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
