# Generated by cpp11: do not edit by hand

create_linestrings_cpp <- function(x1, y1, x2, y2) {
  .Call(`_rrstools_create_linestrings_cpp`, x1, y1, x2, y2)
}

create_face_multilinestrings_cpp <- function(face_edge_hrefs, edge_ids, edge_geoms) {
  .Call(`_rrstools_create_face_multilinestrings_cpp`, face_edge_hrefs, edge_ids, edge_geoms)
}
